### ISSUE TITLE
GitHub Releases Proposal

### ISSUE THREAD

**Issue by bswinnerton** [kumina/libvirt_exporter#12]
Hi there!

I'm working on getting this tool running in a Linux distribution called [Clear Linux](https://clearlinux.org/). It's a very lightweight distribution that has a package manager based around "bundles". I'd like to add this project to one of the supported bundles of that OS, but they [prefer](https://github.com/clearlinux/clr-bundles/issues/61#issuecomment-412351540) that projects included in their packages support GitHub Releases as a way of signifying stable releases of the software.

Is this something that you would all be open to? [Here](https://help.github.com/articles/creating-releases/) is an example of how releases can be made on GitHub.

Thank you for the consideration! 🙇

**Comment by BartVerc** [comment]
I'm sorry that it took so long, but a release has been created :)
