### ISSUE TITLE
The captured memory data is inaccurate？

### ISSUE THREAD

**Issue by circle5848** [kumina/libvirt_exporter#15]

**Comment by circle5848** [comment]
It can be seen that the data captured by the two different modules is the same.

# TYPE libvirt_domain_info_maximum_memory_bytes gauge
libvirt_domain_info_maximum_memory_bytes{domain="c121v0"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v1"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v11"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v12"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v13"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v14"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v15"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v16"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v17"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v2"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v3"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v4"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v5"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v6"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v7"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v8"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c121v9"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c1v58"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c1v66"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c1v67"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c1v68"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c1v69"} 8.589934592e+09
libvirt_domain_info_maximum_memory_bytes{domain="c1v70"} 8.589934592e+09
# HELP libvirt_domain_info_memory_usage_bytes Memory usage of the domain, in bytes.
# TYPE libvirt_domain_info_memory_usage_bytes gauge
libvirt_domain_info_memory_usage_bytes{domain="c121v0"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v1"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v11"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v12"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v13"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v14"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v15"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v16"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v17"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v2"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v3"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v4"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v5"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v6"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v7"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v8"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c121v9"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c1v58"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c1v66"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c1v67"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c1v68"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c1v69"} 8.589934592e+09
libvirt_domain_info_memory_usage_bytes{domain="c1v70"} 8.589934592e+09

**Comment by zhangchengshan** [comment]
@circle5848 Hi, i run into the same issue, do u have solved it ?
