### ISSUE TITLE
Exclude or merge values

### ISSUE THREAD

**Issue by NuxRo** [kumina/libvirt_exporter#24]
Hi,

I'm monitoring a VM which has during this time been stopped and restarted, in the process it has got a new UUID and now my queries are ending up with two sets of values. See below:
https://pastebin.com/raw/bkmgWvfY

Do you know of a way to make Prometheus combine or ignore the uuid values, so it actually gives me the combined added values from all entries (since it's basically the same VM)?

Thanks

**Comment by BartVerc** [comment]
Not sure if this is still relevant, but you could do something like: `sum by ("domain", "instance", "job", "source_bridge", "target_device") (libvirt_domain_interface_stats_receive_bytes_total{domain="vm-39",source_bridge="br0")`.
This will ignore the `uuid`.

**Comment by NuxRo** [comment]
Hey, thanks for getting back to me, even after 1y. :)
"sum" is what I ended up doing indeed.
