### ISSUE TITLE
multi-second response times

### ISSUE THREAD

**Issue by stefreak** [kumina/libvirt_exporter#4]
Hi,

we noticed that libvirt_exporter will need more than 20 seconds for some requests.

When getting some of the stats via virsh directly I noticed some requests taking more time as well, so we decided to reduce our scrape rate because if this, worrying about the impact on libvirtd (unknown to me)

This is probably normal, just wanted to know if you experience the same?

```http_request_duration_microseconds{job="libvirt_exporter",quantile="0.9"}```
![screen shot 2017-05-22 at 17 55 24](https://cloud.githubusercontent.com/assets/139624/26317645/7a4cc7e0-3f18-11e7-9708-5844070c7cb9.png)

```rate(http_requests_total{job="libvirt_exporter"}[5m])```
![screen shot 2017-05-22 at 17 55 17](https://cloud.githubusercontent.com/assets/139624/26317646/7a4e4494-3f18-11e7-9360-701b29bb4549.png)

**Comment by EdSchouten** [comment]
Hi Steffen,

It looks like our libvirt setups respond a lot faster than yours:

![screen shot 2017-05-23 at 11 32 13](https://cloud.githubusercontent.com/assets/736085/26347985/8cdae0de-3fab-11e7-97da-e58879226d61.png)

If this really remains a problem for you, we could consider scraping all domains in parallel, but that would only help if the scraping is not CPU bound on libvirtd's side. If libvirtd is already using 100% CPU while scraping, parallelising would only make it worse.

Could you take a look at libvirtd's CPU usage while scraping?

**Comment by stefreak** [comment]
Hi Ed,

it does not seem to be a real problem for now, but I will definitely dig further when there is some more time for it.

Thanks for sharing your data on this, good to know that your responses come in faster.
