### ISSUE TITLE
GetAllDomainStats build tag?

### ISSUE THREAD

**Issue by vtolstov** [kumina/libvirt_exporter#7]
Hi! I'm need to expose libvirt metrics and want to use get all domain stats becasue i have more than 100 domains on each host and this greatly speedup things.
What do you think about providing build tag to utilize never functions?

**Comment by BartVerc** [comment]
Hi,

That is a good option, using a flag/tag. However, we are currently not in the need of providing this functionality. But you pull request is more than welcome.

**Comment by beddari** [comment]
@BartVerc The point was, could you tag a "stable version" for the current state and document it? Then it would feel more open for PRs with backwards compat breaking changes
